name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run phpcs
        run: vendor/bin/phpcs

      - name: Run psalm
        run: vendor/bin/psalm
